PGREST_ENDPOINT = "http://localhost:8081"
SERVER_NAME = "localhost:8005"
SCHEME = "http"
SENTRY_DSN = ""
PAGE_SIZE_DEFAULT = 20
PAGE_SIZE_MAX = 50
BATCH_SIZE = 50000
DOC_PATH = "/api/doc"
ALLOW_AGGREGATION = [
    "dddddddd-7777-eeee-8888-ffffffffffff",  # without indexes
    "aaaaaaaa-9999-bbbb-1010-cccccccccccc",  # with indexes
]  # list of resource_ids
