PGREST_ENDPOINT = "http://localhost:8080"
SERVER_NAME = "localhost:8005"
SCHEME = "http"
SENTRY_DSN = ""
PAGE_SIZE_DEFAULT = 20
PAGE_SIZE_MAX = 50
BATCH_SIZE = 50000
DOC_PATH = "/api/doc"
ALLOW_AGGREGATION = []
